### ISSUE TITLE
Librewolf Portable still shows after delete the file.

### ISSUE THREAD

**Issue by xbec65** [ltguillaume/librewolf-portable#11]
Hello,

I delete the Librewolf portable files, Also remove all files from User/Appdata/Roaming,I delected the entries from the Registry as well  But, still it shows me this when i pick up Pdf or any kind of file extention. May i know how to remove these files? 

Os: Windows 11 64bit
Librewolf version : 112.0.1-2 
![vcx](https://user-images.githubusercontent.com/86083722/234787944-bde95f0c-797c-481f-ae36-0a1bc06459db.jpg)

Thanks.

**Comment by ltguillaume** [comment]
There shouldn't be any files in AppDate\Roaming, or entries in the registry, that relate to LibreWolf Portable if you run it properly. I'm guessing you pinned LibreWolf to the taskbar at some point? 

As for the Open with...  dialog, this because either you used the script from #9 at some point, or you manually pointed to `LibreWolf-Portable.exe` to open a PDF once. 

Registry items for this should be present, though, so unless they're protected, you should be able to remove them.

**Comment by xbec65** [comment]
Yes, I manually pointed to LibreWolf-Portable.exe to open a PDF once. But, I can't find the registry key for this. If you know please let me know. Thanks.

**Comment by ltguillaume** [comment]
```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.pdf\OpenWithList
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts
HKEY_CURRENT_USER\Software\Classes\Applications\LibreWolf-Portable.exe
```

**Comment by xbec65** [comment]
Thanks, it solved the issues.

**Comment by ltguillaume** [comment]
Could you tell me if you did any of the things below, so that I know what caused the files in AppData\Roaming?

1. Created a new profile from within LibreWolf (e.g. via `about:profiles`)
1. Pinned LibreWolf (actually `librewolf.exe`, not `LibreWolf-Portable.exe`) to the taskbar
1. Ran `librewolf.exe` at some point in time

**Comment by ioc2e3** [comment]
> ```
> HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.pdf\OpenWithList
> HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ApplicationAssociationToasts
> HKEY_CURRENT_USER\Software\Classes\Applications\LibreWolf-Portable.exe
> ```

Thanks for provide this method ...

.
