### ISSUE TITLE
Pin from taskbar

### ISSUE THREAD

**Issue by h8nor** [ltGuillaume/LibreWolf-Portable#4]
Is changing profile settings for the pinned App a feature or a bug?

[explorer.webm](https://user-images.githubusercontent.com/6163937/203590989-3bf79d32-3b80-4309-afcc-fe9e2870d691.webm)

**Comment by ltGuillaume** [comment]
Not a feature, not a bug, you're just confusing pinning `LibreWolf.exe` to the taskbar with pinning `LibreWolf-Portable.exe` to the taskbar.

If you pin a LibreWolf window, opened by `LibreWolf-Portable.exe` to the taskbar, then it'll pin the LibreWolf executable, without the parameter with with location of the portable profile, _not_ the portable launcher.

As such, it'll create a new profile in your user profile directory, instead of using the profile in `Profiles\Default`.

Note that if you drag `LibreWolf-Portable.exe` to the taskbar for pinning instead, it will work, _but_ that icon will not be "used" by LibreWolf itself, so you'll see 2 LibreWolf icons when running.

**Comment by h8nor** [comment]
Thanks for the answer! Now my Profile will not be lost.
Found the shortcut at address `%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar` and added at the end of target `-profile ..\Profiles\Default`
